### ISSUE TITLE
rootless still requires sudo

### ISSUE THREAD

**Issue by begs** [docker/setup-docker-action#152]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-docker-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Hi,
I'm trying to run this action in a runner that uses a distroless image without sudo available.

### Expected behaviour

setup-docker-action installs Docker without needing sudo.

### Actual behaviour

I'm trying to run this action using rootless:
```
with:
  rootless: true
```

but I'm getting an error when it tries to start the Docker daemon.
```
Start Docker daemon
Error: Unable to locate executable file: sudo. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

### YAML workflow

```yaml
- name: Setup Docker
  uses: docker/setup-docker-action@v4
  with:
    rootless: true
```

### Docker daemon logs

```text

```

**Comment by wladpaiva** [comment]
Found the same error while running the action inside a container

```yaml
jobs:
  test-e2e:
    name: 🚥 E2E test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-noble
      options: --user 1001
    steps:
      - name: 🐳 Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          rootless: true
```
