### ISSUE TITLE
Provide binaries using container images

### ISSUE THREAD

**Issue by crazy-max** [docker/setup-docker-action#81]
We current download binaries using tarballs from https://download.docker.com/ when a version is specified in `version` input.

We could use the following images as `version` if user wants to be on edge:
* docker engine: https://hub.docker.com/r/moby/moby-bin
* docker cli: https://hub.docker.com/r/dockereng/cli-bin
* containerd: _none atm_

These images distribute artifacts that we could extract with this action. User could then just set `version` with the list of images to download and extract:

```yaml
      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          version: |
            moby/moby-bin:master
            dockereng/cli-bin:master
```
cc @kiview
